name: WordPress CI (Local Only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run WordPress Coding Standards
        run: vendor/bin/phpcs --standard=WordPress .

      - name: Run PHPUnit Tests (if you have any)
        run: vendor/bin/phpunit || echo "No tests configured"
