name: WordPress CI - Theme Style & Build Check

on:
  push:
    branches: [ main ]
    paths:
      - 'wp-content/themes/mortageoffice/**/*.scss'
      - 'wp-content/themes/mortageoffice/**/*.css'
      - 'wp-content/themes/mortageoffice/**/*.js'
  pull_request:
    branches: [ main ]
    paths:
      - 'wp-content/themes/mortageoffice/**/*.scss'
      - 'wp-content/themes/mortageoffice/**/*.css'
      - 'wp-content/themes/mortageoffice/**/*.js'

jobs:
  theme-style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Lint SCSS/CSS
        run: |
          cd wp-content/themes/mortageoffice
          npx stylelint "**/*.{scss,css}"

      - name: Lint JS
        run: |
          cd wp-content/themes/mortageoffice
          npx eslint "**/*.js"

      - name: Build Theme Styles
        run: |
          cd wp-content/themes/mortageoffice
          npm run build
