name: WordPress CI - Theme Style & Build Check

on:
  push:
    branches: [ main ]
    paths:
      - 'wp-content/themes/mortageoffice/**/*.scss'
      - 'wp-content/themes/mortageoffice/**/*.css'
      - 'wp-content/themes/mortageoffice/**/*.js'
  pull_request:
    branches: [ main ]
    paths:
      - 'wp-content/themes/mortageoffice/**/*.scss'
      - 'wp-content/themes/mortageoffice/**/*.css'
      - 'wp-content/themes/mortageoffice/**/*.js'

jobs:
  theme-style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Lint SCSS/CSS
        run: npx stylelint "wp-content/themes/mortageoffice/**/*.{scss,css}"

      - name: Lint JS
        run: npx eslint "wp-content/themes/mortageoffice/**/*.js"

      - name: Build Theme Styles
        run: npm run build
